### ISSUE TITLE
Bug report - Error on startup after last update.

### ISSUE THREAD

**Issue by Yolakalemowa** [brogers5/chocolatey-package-localsend.portable#1]
**Describe the bug**

Hello,
I have LS downloaded through chocolatey. After updating to v1.15.3, when I open it, I'm greeted with a screen with the following error:

LocalSend 1.15.3 (53)

Error: PathAccessException: Cannot open file, path = 'C:\ProgramData\chocolatey\lib\localsend.portable\tools\settings.json' (OS Error: Access is denied.
, errno = 5)

#0 _Link.throwIfError (dart:io/link.dart:254)
https://github.com/localsend/localsend/issues/1 _File.openSync (dart:io/file_impl.dart:490)
https://github.com/localsend/localsend/issues/2 _File.writeAsBytesSync (dart:io/file_impl.dart:644)
https://github.com/localsend/localsend/issues/3 _File.writeAsStringSync (dart:io/file_impl.dart:668)
https://github.com/localsend/localsend/issues/4 SharedPreferencesFile._write (package:localsend_app/util/shared_preferences/shared_preferences_file.dart:72)
https://github.com/localsend/localsend/issues/5 SharedPreferencesFile.setValue (package:localsend_app/util/shared_preferences/shared_preferences_file.dart:63)
https://github.com/localsend/localsend/issues/6 PersistenceService.initialize (package:localsend_app/provider/persistence_provider.dart:122)

https://github.com/localsend/localsend/issues/7 preInit (package:localsend_app/config/init.dart:60)

https://github.com/localsend/localsend/issues/8 main (package:localsend_app/main.dart:23)

Is it an error on my end? It was working fine before.

**To reproduce**
    Have LS 1.15.2 downloaded from chocolatey
    upgrade to latest 1.15.3 through chocolatey
    open local send
    See error message abovev

**Expected behavior**
start normally

**Screenshots**
![353508245-cce82c5a-5022-43ba-912e-6d9d0bae7200](https://github.com/user-attachments/assets/8d0a405a-13b7-4991-ab51-033a7146cae7)

**Desktop**:
Using Win10.
Chocolatey

note: [link ](https://github.com/localsend/localsend/issues/1589 )to same issue opened localsend github

**Comment by slrgt** [comment]
i got this error and after running it as administrator now when it auto starts i cant minimize or close the window (reposted from the localsend github)

**Comment by brogers5** [comment]
@slrgt, I can reproduce your issue on a clean VM without involving the Chocolatey package. The issue you're seeing is a bug in LocalSend itself.

**Comment by slrgt** [comment]
Ah ok well then good thing i posted it on the issue there as well haha

**Comment by Tienisto** [comment]
What path does it say @brogers5 (if you didn't destroyed the VM yet)

**Comment by brogers5** [comment]
@Tienisto, I have since reverted to an earlier checkpoint, but was able to reproduce @slrgt's problem again. In this scenario, LocalSend had launched successfully, but does not honor a request to close the window. From what I'm seeing, it looks like LocalSend is aborting the window closure when a save failure occurs.

In Process Monitor, I am seeing a call to `CreateFile` targeting `settings.json` failing when this happens. I assume this is because the process is attempting to write the current configuration to `settings.json` before terminating.

In the context of an autostart configuration with the Chocolatey package, the failure would be `ACCESS_DENIED`, which makes sense since LocalSend would presumably be launching without an elevated user token.

In my case, I suspect the root cause was something intermittent like a sharing violation, as I have not been successful with reproducing it again in a real world scenario. However, if I manually open an unshared file handle against `settings.json` to force a `SHARING_VIOLATION` failure, LocalSend will behave in a similar manner.

For the latter scenario, you could create a `FileStream` object in PowerShell to reliably reproduce:

```ps1
#TODO: Change directory to portable LocalSend directory
$settingsFilePath = Join-Path -Path (Get-Location) -ChildPath 'settings.json'
$fileStream = New-Object IO.FileStream $settingsFilePath, 'Open', 'ReadWrite', 'None'
```
